### ISSUE TITLE
Problem parsing knife.rb

### ISSUE THREAD

**Issue by nickpeirson** [bmarini/health_inspector#1]
We're getting the error

```
./.chef/knife.rb:22:in `from_file': uninitialized constant Chef::Knife (NameError)
from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/mixlib-config-1.1.2/lib/mixlib/config.rb:37:in `instance_eval'
from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/mixlib-config-1.1.2/lib/mixlib/config.rb:37:in `from_file'
from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/health_inspector-0.0.4/lib/health_inspector/context.rb:18:in `configure'
...
```

when we try to run `health_inspector inspect` against our repo and the cause seems to be this section from our knife.rb

```
class Chef::Knife::Ec2ServerCreate < Chef::Knife
  alias :original_run :run

  def run
    @initial_sleep_delay = 30
    puts "sleeping #{@initial_sleep_delay} this time"

    original_run
  end
end
```

When this section is commented out it works.

**Comment by bmarini** [comment]
Try adding `require "chef/knife"` above your subclass, I think that'll fix it.

**Comment by nickpeirson** [comment]
That pointed me in the right direction. Adding both of the following lines fixed it:

```
require "chef/knife"
require "chef/knife/ec2_server_create"
```

Is it possible to grab knifes requires automatically to stop other people seeing similar issues, assuming other people are subclassing classes in there knife.rb?

I'm also not sure subclassing in the knife.rb follows best practice, so I'm open to advice on a better approach, although it may be a limitation of the `Ec2ServerCreate` class's configuration? I know just enough ruby to get by in chef (php being the language I use mostly), so this maybe unfounded criticism of `Ec2ServerCreate` :)

**Comment by bmarini** [comment]
I'm going to call this an edge case. Adding monkey patches inside your knife.rb is not a best practice, and would probably surprise most chef users. Better to use your own fork of the knife-ec2 gem/knife plugin
