### ISSUE TITLE
Console Output on Windows

### ISSUE THREAD

**Issue by dpetzel** [bmarini/health_inspector#3]
This is a really great tool!!. Thanks for putting this together. I noticed when I run this on my Windows 7 laptop, the output is garbled like `←[93m  exists on server but not locally←[0m`

I'm pretty new to Ruby so its possible, I just don't have things configured properly, but I did some Google foo and poked around the source and near as I can figure the issue is that color.rb is trying to print some ASCII output?

It seems there are a couple libraries that allow ANSI output on a Win32 platform, but I'm not familiar enough with any of them to attempt to hack a patch together. It would be great if the output was formatted in such a way that your color coding can co-exist with a windows console.

Thanks again for this great tool

**Comment by bmarini** [comment]
Hey thanks for trying it out! You are right about the ansii output. I don't have a windows machine to test this out on, but I'll look into at least disabling the colors on windows.

**Comment by bmarini** [comment]
@dpetzel colors can now be disabled in 0.5.0 with the --no-color option.
